import { LevelArrow } from '../game-logic/level-arrow';
import { LevelInfo } from '../levels/level-info';
import { Game } from '../player/game';
import { PlayerControls } from '../player/player-controls';
import { PlayerOverlay } from '../player/player-overlay';
import { PlayerUI } from '../player/player-ui';
export declare class LevelPage {
    readonly game: Game;
    readonly playerUI: PlayerUI;
    readonly playerControls: PlayerControls;
    readonly playerOverlay: PlayerOverlay;
    readonly info: LevelInfo;
    levelArrows: LevelArrow[];
    private canvasDiv;
    private isDeleted;
    private levelRights;
    private scoreHolder;
    private prograssBar;
    private playButton;
    private sidePanel;
    private levelTestHolder;
    private levelTestBar;
    private tutorialDataStep;
    private tutorialData;
    private levelTesting;
    constructor(info: LevelInfo);
    showTutorial(payload?: (panel: HTMLDivElement) => void): Promise<void>;
    nextTutorialStep(): void;
    dispose(): void;
    setProgress(progress: number): void;
    initLevel(needPlayButton?: boolean): void;
    restartLevel(): void;
    private updateLevelArrows;
    private complete;
    private resize;
    private runLevel;
    private update;
    private replaceInlineArrows;
    private replaceInlineKeys;
    private replaceInlineSpoilers;
}
