import { Game } from './game';
import { GameHistory } from './game-history';
import { PlayerAccess } from './player-access';
import { PlayerUI } from './player-ui';
export declare class PlayerControls {
    private playerAccess;
    private flipDirection;
    private mousePosPrev;
    private mousePressedPrev;
    private wheelDelta;
    private mouseHandler;
    private keyboardHandler;
    private game;
    private playerUI;
    private history;
    private freeCursor;
    private activeArrowType;
    private arrowStartPoint;
    private controlsHints;
    private maxZoomOut;
    private keyboardZoomVelocity;
    private keyboardMoveVelocity;
    constructor(cnv: HTMLCanvasElement, game: Game, playerUI: PlayerUI, history?: GameHistory | null);
    updatePlayerAccess(playerAccess: Partial<PlayerAccess>): void;
    getPlayerAccess(): PlayerAccess;
    update(): void;
    dispose(): void;
    private updateControlsHints;
    private onPaste;
    private onPasteError;
    private keyDownCallback;
    private getArrowByMousePosition;
    private selectToolBarArrow;
    private takeArrow;
    private takeCursor;
    private keyUpCallback;
    private leftClickCallback;
    private wheelCallback;
    private pasteEvent;
    private copyEvent;
    private undo;
    private redo;
    private moveCamera;
    private handleZoom;
    private togglePause;
    private setArrows;
    private deleteArrow;
    private deleteSelectedArrows;
    private rotateArrow;
    private flipArrow;
    private selectArrows;
    private copyArrows;
    private pasteArrows;
    private cutArrows;
    private pickArrow;
    private runOneTick;
    private clearSignals;
}
